name: Release Test
on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  Release:
    if: github.event.review.state == 'APPROVED' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build

      - name: Publish
        run: pnpx pkg-pr-new publish './packages/*'
