name: Release

on: workflow_dispatch

jobs:
  checks:
    uses: ./.github/workflows/ci.yml

  release:
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Tag and Release
        run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          pnpm ci:version
          git add .
          git commit -m "chore(release): publish"
          pnpm build
          pnpm ci:tag
          pnpm ci:publish
          git push && git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
